version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    container_name: api-dev
    expose:
      - "9000"
    ports:
      - 9000:9000
    volumes:
      - ./:/data/api-dev
      - /data/api-dev/vendor
    networks:
      - default
    working_dir: /data/api-dev/

  nginx:
    container_name: nginx_api-dev
    image: nginx:1.16.0
    ports:
      - 8001:80
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  db-apidev:
    image: mysql:5.7.22
    container_name: db-apidev
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=apidev
    volumes:
      - ./.docker/database:/var/lib/mysql
    command: --innodb-use-native-aio=0
    ports:
      - 3308:3306
    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge
